### LabelEncoder
* Encode target labels with value between 0 and n_classes-1.

* This transformer should be used to encode target values, i.e. y, and not the   input X.

* fit(y)

* Fit label encoder.

* fit_transform(y)

* Fit label encoder and return encoded labels.

* get_params([deep])

* Get parameters for this estimator.

* inverse_transform(y)

* Transform labels back to original encoding.

* set_params(**params)

* Set the parameters of this estimator.

* transform(y)

* Transform labels to normalized encoding.

In [86]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', "냉장고", "전자렌지", "컴퓨터","선풍기", "선풍기","믹서", "믹서"]

# LabelEncoder 를 객체로 생성한 후, fit() 과 transform()으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:' , labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [87]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [88]:
print('디코딩 원본 값:', encoder.inverse_transform([1,5,0,2,3,4,1,0]))

디코딩 원본 값: ['냉장고' '컴퓨터' 'TV' '믹서' '선풍기' '전자렌지' '냉장고' 'TV']


1. Survived, Sex, Age, Embarked 컬럼만 이용하려 한다.
2. 피처는 Sex, Age, Embarked 사용
3. 레이블은 Survived 사용하여 지도 학습을 하려고 한다.
4. 데이터의 전처리가 필요한 상황이라 데이터 전처리를 해야 하는데 결측치가 관찰 되어서 결측치 처리를 해야 하고
5. 문자열이 보여서 인코딩을 해줘야한다.
6. 결측치는 평균값으로 인코딩은 labelencoding을 이용하여 처리한 결과를 데이터 프레임으로 출력

1. 판다스를 이용해서 csv 읽어오기
2. 필요한 칼럼만 남기고 drop
3. fillna를 활용하여 결측치 처리 (mean) -> 성별은 남자, 나이는 평균 , Embarked 는 S
4. LabelEncoder 를 활용

In [16]:
import pandas as pd
t_1 = pd.read_csv("./train.csv")
t_1.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  Parch     Ticket  Fare Cabin Embarked
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1      0  A/5 21171  7.25   NaN        S

In [26]:
t_2 = pd.DataFrame(t_1)

In [33]:
t_3=t_2.drop(['PassengerId', 'Pclass', 'Name', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin'], axis = 1)

In [54]:
t_3['Sex']=t_3['Sex'].fillna('male')
t_3['Age']=t_3['Age'].fillna(t_3['Age'].mean())
t_3['Embarked']=t_3['Embarked'].fillna('S')

In [63]:
encoder = LabelEncoder()
encoder.fit(t_3.Sex)
labels = encoder.transform(t_3.Sex)
t_3.Sex = labels

Survived  Sex        Age Embarked
0           0    1  22.000000        S
1           1    0  38.000000        C
2           1    0  26.000000        S
3           1    0  35.000000        S
4           0    1  35.000000        S
..        ...  ...        ...      ...
886         0    1  27.000000        S
887         1    0  19.000000        S
888         0    0  29.699118        S
889         1    1  26.000000        C
890         0    1  32.000000        Q

[891 rows x 4 columns]

In [65]:
encoder = LabelEncoder()
encoder.fit(t_3.Embarked)
labels = encoder.transform(t_3.Embarked)
t_3.Embarked = labels

Survived  Sex        Age  Embarked
0           0    1  22.000000         2
1           1    0  38.000000         0
2           1    0  26.000000         2
3           1    0  35.000000         2
4           0    1  35.000000         2
..        ...  ...        ...       ...
886         0    1  27.000000         2
887         1    0  19.000000         2
888         0    0  29.699118         2
889         1    1  26.000000         0
890         0    1  32.000000         1

[891 rows x 4 columns]

In [75]:
t_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       891 non-null    float64
 3   Embarked  891 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 28.0 KB


### OneHotEncoder
* sklearn.preprocessing.OneHotEncoder
* OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)

In [76]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [94]:

encodero = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

#원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### get_dummies
* pandas.get_dummies
* pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)


In [98]:
import pandas as pd 
df = pd.read_csv("./train.csv")
df.drop(columns = ['PassengerId','Pclass','Name','SibSp', 'Parch','Ticket','Fare','Cabin'],inplace=True)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna('S')

In [100]:
data = df.loc[:,'Embarked']

In [101]:
data

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [102]:
dummy_embark=pd.get_dummies(data)

In [108]:
dummy_data = pd.get_dummies(df[['Sex', 'Embarked']])

In [109]:
dummy_data

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [114]:
dummy_df = pd.concat([df, dummy_data], axis = 1 )

In [115]:
dummy_df.drop(columns=['Sex','Embarked'], inplace=True)

In [116]:
dummy_df

Survived        Age  Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0  22.000000           0         1           0           0           1
1           1  38.000000           1         0           1           0           0
2           1  26.000000           1         0           0           0           1
3           1  35.000000           1         0           0           0           1
4           0  35.000000           0         1           0           0           1
..        ...        ...         ...       ...         ...         ...         ...
886         0  27.000000           0         1           0           0           1
887         1  19.000000           1         0           0           0           1
888         0  29.699118           1         0           0           0           1
889         1  26.000000           0         1           1           0           0
890         0  32.000000           0         1           0           1           0

[891 rows x 7 columns]